### ISSUE TITLE
contador de corazones

### ISSUE THREAD

**Issue by akizzej** [natichan/scl-2018-05-bc-core-pm-socialnetwork#1]
Naty  ojo aún se cuentan los corazones de todas las publicaciones en el primer post. 
revisalo please.

**Comment by natichan** [comment]
Gracias Jessica, trabajaré en eso hoy :smile:

**Comment by natichan** [comment]
Fije un milestone para terminar esta función, por ahora cerrare el issue pero está en mi radar.

Gracias Jess :smiley_cat:
